src/task_list/urls.py
from django.conf.urls import patterns, url, include
from task_list import views

urlpatterns = patterns("",
    url(r"^/?$", views.task_list, name="task_list"),
    url(r"^register/$", views.register_user, name="register_user"),
    url(r"^login/$", views.login_user, name="login_user"),
    url(r"^logout/$", views.logout_user, name="logout_user"),
    url(r"^about/$", views.about, name="about"),
    url(r"^close_task/(\d+)$", views.close_task, name="close_task"),
    url(r"^add_task/$", views.add_task, name="add_task"),
    url(r"^edit_task/(\d+)$", views.edit_task, name="edit_task"),
    url(r"^delete_task/(\d+)$", views.delete_task, name="delete_task"),
)

src/task_list_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'task_list_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^task_list/', include('task_list.urls')),
)

src/task_list/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Task(models.Model):
    """Task Datamodel"""
    user = models.ForeignKey(User, related_name="creator")
    title = models.CharField(max_length=128)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True, blank=True)
    is_done = models.BooleanField(default=False)
    status_changed_by = models.ForeignKey(User, default=None, null=True,
                                          blank=True,
                                          related_name="changed_by")

    def __unicode__(self):
        return self.title

src/task_list/forms.py
from django import forms
from django.contrib.auth.models import User
from models import Task

class UserForm(forms.ModelForm):
    """User registration form"""
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class AddTaskForm(forms.ModelForm):
    """Form for adding a Task"""
    class Meta:
        model = Task
        fields = ("title", "description")

src/task_list/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.models import User
from forms import UserForm, AddTaskForm
from models import Task


# Create your views here.
@login_required(login_url="/task_list/login")
def task_list(request):
    """
    Task list page.

    First checks whether user specified completed tasks are to be hidden via a
    query string paramter. Then creates a list of dicts of each user and their
    tasks which is handled by the template.

    """
    # First check if user specified completed searches to be hidden via query
    # string
    if request.GET.get("hide_completed") and int(request.GET
                                                 .get("hide_completed")):
        filter_completed = True
    else:
        filter_completed = False

    user_tasks = []
    # we want the currently logged in user and their tasks (if any) first
    if filter_completed:
        user_tasks.append({"user": request.user, "tasks": Task.objects
                           .filter(user=request.user, is_done=False)})
    else:
        user_tasks.append({"user": request.user, "tasks": Task.objects
                           .filter(user=request.user)})

    # Do same for rest of users!
    for user in User.objects.all():
        if user == request.user:
            continue

        if filter_completed:
            user_tasks.append({"user": user, "tasks": Task.objects
                               .filter(user=user, is_done=False)})
        else:
            user_tasks.append({"user": user, "tasks": Task.objects
                               .filter(user=user)})
    return render(request, "index.html", {"user_tasks": user_tasks,
                                          "filter_completed": filter_completed})


def about(request):
    """About page"""
    return render(request, "about.html")


def register_user(request):
    """User registration"""
    registered = False
    form_errors = None
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            form_errors = str(user_form.errors)
    else:
        user_form = UserForm()

    return render(request, "register.html", {"user_form": user_form,
                                             "registered": registered,
                                             "form_errors": form_errors})


@login_required
def logout_user(request):
    """Logout user and redirect to index page"""
    logout(request)
    return HttpResponseRedirect("/task_list")


def login_user(request):
    """User login"""
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/task_list')
            else:
                return HttpResponse("You account is disabled, please contact "
                                    "the site administrator.")
        else:
            print "Invalid login details: {0}, {1}".format(username, password)
            return render(request, "login_fail.html", status=401)

    else:
        return render(request, "login.html")


@login_required
def add_task(request):
    """Add a task"""
    task_added = False
    form_errors = None
    if request.method == "POST":
        task_form = AddTaskForm(data=request.POST)
        if task_form.is_valid():
            task = task_form.save(commit=False)
            task.user = request.user
            task.save()
            task_added = True
        else:
            form_errors = str(task_form.errors)
    else:
        task_form = AddTaskForm()

    return render(request, "add_task.html", {"task_form": task_form,
                                             "task_added": task_added,
                                             "form_errors": form_errors})


@login_required
def edit_task(request, task_id):
    """
    Edit a task.

    If user is trying to edit someone else's task (should not be possible via
    UI) then send 403 error.

    """
    saved_task = Task.objects.get(id=task_id)
    # Avoid getting a SimpleLazyObject
    current_user = (request.user._wrapped if hasattr(request.user, '_wrapped')
                    else request.user)
    if current_user != saved_task.user:
        raise PermissionDenied
    task_edited = False
    form_errors = None
    if request.method == "POST":
        task_form = AddTaskForm(data=request.POST, instance=saved_task)
        if task_form.is_valid():
            task = task_form.save(commit=False)
            # Get radio button values from POST data as we're re-using the
            # AddTaskForm
            task.is_done = True if int(request.POST["task_status"]) else False
            task.save()
            task_edited = True
        else:
            form_errors = str(task_form.errors)
    else:
        task_form = AddTaskForm()

    return render(request, "edit_task.html", {"task_form": task_form,
                                              "task_edited": task_edited,
                                              "task": saved_task,
                                              "form_errors": form_errors})


@login_required
def close_task(request, task_id):
    """
    Toggle the status of a Task (assuming user should be able to close
    others'tasks)
    """
    task = Task.objects.get(id=task_id)
    if not task.is_done:
        task.is_done = True
        task.status_changed_by = request.user
        task.save()
    return HttpResponseRedirect("/task_list")


@login_required
def delete_task(request, task_id):
    """Delete a task.

    If user is trying to delete someone else's task (should not be possible via
    UI) then send 403 error.
    """
    saved_task = Task.objects.get(id=task_id)
    # Avoid getting a SimpleLazyObject
    current_user = (request.user._wrapped if hasattr(request.user, '_wrapped')
                    else request.user)
    if current_user != saved_task.user:
        raise PermissionDenied
    saved_task.delete()
    return render(request, "delete_task.html")

src/task_list/templates/about.html
{% extends "base.html" %}
{% block title %}About{% endblock %}
{% block body_block %}
<h1>About</h1>
<p>This is a simple web-based task list application</p>
{% endblock %}

src/task_list/templates/add_task.html
{% extends "base.html" %}
{% block title %}Add Task{% endblock %}
{% block body_block %}
{% if task_added %}
<p>You have succesfully created a task!</p>
<a href="/task_list">Go to task list (will redirect automatically in 2 seconds)</a>
<script>
// Redirect after 2 seconds
$(document).ready(function() {
  window.setTimeout(function() {
    location.href = "/task_list/";
  }, 2000);
});
</script>

{% else %}
<div class="container" style="width:350px; margin-left:0">
  <form role="form"  method="post" action=".">
    {% csrf_token %}
    <h2 class="form-signin-heading">Add Task</h2>
    
    <div class="form-group" >
      <p class="required"> <label for="id_title">Title:</label>
      <input class="form-control" id="id_title" maxlength="30" name="title"
      type="text" placeholder="Enter title"/></p>
    </div>
    
    <div class="form-group" >
      <p class="required"> <label for="id_description">Description:</label>
      <input class="form-control" id="id_description" maxlength="30" name="description"
      type="text" placeholder="Enter description"/></p>
    </div>

    {% if form_errors %}
    <p>{{form_errors}}</p>
    {% endif %}
    
    <button type="submit" class="btn btn-default">Submit</button>
  </form>
</div>
{% endif %}
{% endblock %}

src/task_list/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="//getbootstrap.com/favicon.ico">
 
    <title>{% block title %} {% endblock %} | Task List</title>
 
    <link href="//getbootstrap.com/docs/3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="//getbootstrap.com/docs/3.3/examples/dashboard/dashboard.css" rel="stylesheet">
    <script src="//code.jquery.com/jquery-3.1.1.slim.min.js"></script>
 
    <!--[if lt IE 9]>
     <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
     <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
          data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/task_list/">Task List</a>
        </div>
        
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'task_list' %}">Home</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'logout_user' %}?next=/task_list/">Logout</a></li>
          {% else %}
          <li><a href="{% url 'register_user' %}">Register</a></li>
          <li><a href="{% url 'login_user' %}">Login</a></li>
          {% endif %}
          <li><a href="{% url 'about' %}">About</a></li>
          
          </ul>
        </div>
      </div>
    </div>
        
    <div class="container-fluid">
      <div style="padding-top: 2em">
      {% block body_block %}{% endblock %}
      </div>
    </div>
    
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//getbootstrap.com/docs/3.3/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="//getbootstrap.com/docs/3.3/assets/js/ie10-viewport-bug-workaround.js"></script>
 </body>
</html>

src/task_list/templates/delete_task.html
{% extends "base.html" %}
{% block title %}Add Task{% endblock %}
{% block body_block %}
<p>Task deleted!</p>
<a href="/task_list">Go to task list (will redirect automatically in 2 seconds)</a>
<script>
// Redirect after 2 seconds
$(document).ready(function() {
  window.setTimeout(function() {
    location.href = "/task_list/";
  }, 2000);
});
</script>
{% endblock %}

src/task_list/templates/edit_task.html
{% extends "base.html" %}
{% block title %}Add Task{% endblock %}
{% block body_block %}
{% if task_edited %}
<p>You have succesfully edited your task!</p>
<a href="/task_list">Go to task list (will redirect automatically in 2 seconds)</a>
<script>
// Redirect after 2 seconds
$(document).ready(function() {
  window.setTimeout(function() {
    location.href = "/task_list/";
  }, 2000);
});
</script>

{% else %}
<div class="container" style="width:350px; margin-left:0">
  <form role="form"  method="post" action="./{{task.id}}">
  {% csrf_token %}
    <h2 class="form-signin-heading">Edit Task</h2>
    
    <div class="form-group" >
      <p class="required"> <label for="id_title">Title:</label>
        <input class="form-control" id="id_title" maxlength="30" name="title"
          type="text" value={{task.title}}>
      </p>
    </div>
    
    <div class="form-group" >
      <p class="required"> <label for="id_description">Description:</label>
        <input class="form-control" id="id_description" maxlength="30" name="description"
          type="text" value={{task.description}} />
      </p>
    </div>

    {% if task.is_done %}
    <div class="radio">
      <label><input type="radio" name="task_status" value="0">Task not done</label>
    </div>
    <div class="radio">
      <label><input type="radio" name="task_status" value="1" checked="checked">Task done</label>
    </div>
    
    {% else %}
    <div class="radio">
      <label><input type="radio" name="task_status" value="0" checked="checked">Task not done</label>
    </div>
    <div class="radio">
      <label><input type="radio" name="task_status" value="1" >Task done</label>
    </div>
    {% endif %}

    {% if form_errors %}
    <p>{{form_errors}}</p>
    {% endif %}
    
    <button type="submit" class="btn btn-default">Submit</button>
  </form>
</div>
{% endif %}
{% endblock %}

src/task_list/templates/index.html
{% extends "base.html" %}
{% block title %}All Tasks{% endblock %}
{% block body_block %}
<script>
$(document).ready(function() {
  close_task();
  delete_task();
  hide_completed_tasks();
});

// Hide completed button (redirect to url)
function hide_completed_tasks() {
  $(".hide-completed").click(function(e) {
      window.location.href = "/task_list/?hide_completed=1"
  }); 
}

// Delete a task
function delete_task(){
  $("span.delete-task").click(function(e) {
    e.preventDefault();
    var delete_task = confirm("Are you sure you want to delete this task?");
    if (delete_task) {
      var task_id = $(this).attr("data-task-id");
      var delete_url = "/task_list/delete_task/" + task_id;
      console.log("Delete task url: " + delete_url);
      window.location.href = delete_url;
    }
  });
}

// Close a task
function close_task(){
  $("span.status").click(function(e) {
    e.preventDefault();
    var task_id = $(this).attr("data-task-id");
    var close_url = "/task_list/close_task/" + task_id;
    console.log("Close task url: " + close_url);
    window.location.href = close_url;
  });

  $("span.status_done").click(function(e) {
    e.preventDefault();
  });
}
</script>

<div class="container" style="width:450px; margin-left:0">
  <div style="margin-left:340px; padding-bottom:3px">
    <a href="/task_list/add_task">Add task <span class="glyphicon glyphicon-plus">
    </span></a>
  </div>

  {% for user_task_dict in user_tasks %}
  <!-- User title -->
  <a href="#" class="list-group-item active">
    <span class="glyphicon glyphicon-user"></span>
    {{user_task_dict.user}}
  </a>

  <!-- Tasks -->
  {% if user_task_dict.tasks %}
  {% for task in user_task_dict.tasks %}
  <!-- This is to add clickable edit and delete glyphs and a clickable badge to close a task -->
  <a title="Edit task" href="/task_list/edit_task/{{task.id}}" class="list-group-item">
    <span class="glyphicon glyphicon-file"></span>
    {{task.title}}
    
    {% if not task.is_done %}
    <span style="float: right" title="Mark done" data-task-id="{{task.id}}" class="badge status">
      Not Done
    </span>
    
    {% else %}
    <span title="Task closed by {{task.status_changed_by}}"
    data-task-id="{{task.id}}" class="badge status_done">
      Done
    </span>
    {% endif %}

    <!-- Delete and edit symbols (only show if tasks were created by active user) -->
    {% if task.user == user %}
    <span title="Delete task" style="float: right; padding-right:5px"
      class="glyphicon glyphicon-remove delete-task"
      data-task-id="{{task.id}}">
    </span>
    <span style="float: right; padding-right:5px" class="glyphicon glyphicon-pencil edit_task"
      data-task-id="{{task.id}}">
    </span>
    {% endif %}

  </a>
  {% endfor %}

  <!-- No saved tasks -->
  {% else %}
  <a href="#" class="list-group-item">No saved tasks</a>
  {% endif%}
  <br />
  {% endfor %}

  {% if not filter_completed %}
  <button class="btn btn-default hide-completed">Hide Completed Tasks</button>
  {% endif %}
</div>
{% endblock %}

src/task_list/templates/login.html
{% extends "base.html" %}
{% block title %}User login{% endblock %}
{% block body_block %}
<link href="//getbootstrap.com/docs/3.3/examples/signin/signin.css" rel="stylesheet">
<div class="container" style="width:300px; margin: 0 auto; padding-left: 3em">
<h2 class="form-signin-heading">Please sign in</h2>
</div>
<form class="form-signin" role="form" id="login_form" method="POST" action="/task_list/login/">
{% csrf_token %}
<input class="form-control" placeholder="Username" id="id_username" maxlength="254" name="username" type="text" required autofocus=""/>
<input type="password" class="form-control" placeholder="Password" id="id_password" name="password"  required />
<button class="btn btn-lg btn-primary btn-block" type="submit" value="Submit" >Sign in</button>
</form>
{% endblock %}

src/task_list/templates/login_fail.html
{% extends "base.html" %}
{% block title %}Registration{% endblock %}
{% block body_block %}
<p>Login failed!</p>
<a href="/task_list/login">Go back to login page</a>
{% endblock %}

src/task_list/templates/register.html
{% extends "base.html" %}
{% block title %}Registration{% endblock %}
{% block body_block %}

{% if registered %}
<p>You have successfully registered!</p>
<a href="/task_list">Go to login (will redirect automatically in 2 seconds)</a>

<script>
// Redirect after 2 seconds
$(document).ready(function() {
  window.setTimeout(function() {
    location.href = "/task_list/login";
  }, 2000);
});
</script>

{% else %}
<div class="container" style="width:350px; margin-left:0">
  <form role="form"  method="post" action=".">
    {% csrf_token %}
    <h2 class="form-signin-heading">Register</h2>
   
    <div class="form-group" >
      <p class="required"> <label for="id_username">Username:</label>
        <input class="form-control"  id="id_username" maxlength="30"
          name="username" type="text"  placeholder="Enter username"/>
      </p>
    </div>

    <div class="form-group">
      <p class="required"><label for="id_email">E-mail:</label>
        <input class="form-control" id="id_email" name="email"
          type="email" placeholder="Enter email" />
      </p>
    </div>
 
    <div class="form-group">
      <p class="required"><label for="id_password">Password:</label>
        <input class="form-control" id="id_password" name="password"
          type="password" placeholder="Enter password" />
      </p>
    </div>

    {% if form_errors %}
    <p>{{form_errors}}</p>
    {% endif %}

    <button type="submit" class="btn btn-default">Submit</button>
 </form>
</div>
{% endif %}
{% endblock %}